# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go get ./...

builds:
  -
    main: cmd/prometheus-aggregate-exporter/main.go
    binary: prometheus-aggregate-exporter
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}-{{ .Version }}.el6.{{ .Arch }}"
  maintainer: Kenneth Pianeta <kjpianeta@gmail.com>
  replacements:
    amd64: x86_64
  description: "Prometheus exporter to aggregate multiple exporters running into one target endpoint."
  license: MIT
  formats:
    - rpm
  bindir: /usr/bin
  empty_folders:
    - /var/log/prometheus
    - /var/run/prometheus
    - /etc/sysconfig/logrotate.d
  files:
    "rpm/files/prometheus-aggregate-exporter.initd": "/etc/init.d/prometheus-aggregate-exporter"
    "rpm/files/prometheus-aggregate-exporter.logrotate": "/etc/sysconfig/logrotate.d/prometheus-aggregate-exporter"
  config_files:
    "rpm/config/prometheus-aggregate-exporter.env": "/etc/sysconfig/prometheus/prometheus-aggregate-exporter.env"
    "rpm/config/prometheus-aggregate-exporter-config.yml": "/etc/sysconfig/prometheus/prometheus-aggregate-exporter-config.yml"
  scripts:
    preinstall: "rpm/scripts/preinstall.sh"
    postinstall: "rpm/scripts/postinstall.sh"
    preremove: "rpm/scripts/preremove.sh"
    postremove: "rpm/scripts/postremove.sh"
